name: CI

on:
  pull_request:
    branches:
      - "dev"
  workflow_dispatch:

jobs:
  release_and_tag:
    runs-on: ubuntu-latest
    if: startsWith(github.head_ref, 'feature')
    environment:
      name: dev
      url: "https://alanmynah.com/"
    steps:
      - name: Extract branch name
        shell: bash
        run: |
          echo ${{ github.ref_name }}
          echo ${{ github.head_ref }}
      - name: Checkout branch
        uses: actions/checkout@v3
