name: CI

on:
  push:
    branches: [main]

jobs:
  # merge-branch:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@master

  #     - name: Merge staging -> uat
  #       uses: devmasx/merge-branch@master
  #       with:
  #         type: now
  #         target_branch: uat
  #         github_token: ${{ github.token }}
  release_and_tag:
    runs-on: ubuntu-latest
    steps:
      # - name: Extract commit hash
      #   shell: bash
      #   run: echo "##[set-output name=commit_sha;]$(echo ${GITHUB_SHA})"
      #   id: extract_hash
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        with:
          title: "release:${GITHUB_SHA}"
